
const map = [
  {x: 0, y: 1, room: "Hallway"},
  {x: 1, y: 1, room: "Hallway"},
  {x: 2, y: 1, room: "Hallway"},
  {x: 3, y: -1, room: "Hallway"},
  {x: 3, y: -2, room: "Hallway"},
  {x: 3, y: -3, room: "Hallway"},
  {x: 3, y: -4, room: "Hallway"},
  {x: 3, y: -5, room: "Hallway"},
  {x: 3, y: -6, room: "Hallway"},
  {x: 3, y: -7, room: "Hallway"},
  {x: 3, y: -8, room: "Hallway"},
  {x: 3, y: 0, room: "Hallway"},
  {x: 3, y: 1, room: "Hallway"},
  {x: 4, y: -8, room: "Hallway"},
  {x: 4, y: -7, room: "Hallway"},
  {x: 4, y: -6, room: "Hallway"},
  {x: 4, y: -5, room: "Hallway"},
  {x: 4, y: -4, room: "Hallway"},
  {x: 4, y: -3, room: "Hallway"},
  {x: 4, y: -2, room: "Hallway"},
  {x: 4, y: -1, room: "Hallway"},
  {x: 4, y: 0, room: "Hallway"},
  {x: 4, y: 1, room: "Hallway"},
  {x: 4, y: 2, room: "Hallway"},
  {x: 5, y: 0, room: "Hallway"},
  {x: 5, y: 1, room: "Hallway"},
  {x: 5, y: 2, room: "Hallway"},
  {x: 6, y: 0, room: "Hallway"},
  {x: 6, y: 1, room: "Hallway"},
  {x: 6, y: 2, room: "Hallway"},
  {x: 7, y: 0, room: "Hallway"},
  {x: 7, y: 1, room: "Hallway"},
  {x: 7, y: 2, room: "Hallway"},
  {x: 8, y: 0, room: "Hallway"},
  {x: 8, y: 1, room: "Hallway"},
  {x: 8, y: 2, room: "Hallway"},
  {x: 9, y: 0, room: "Hallway"},
  {x: 9, y: 1, room: "Hallway"},
  {x: 9, y: 2, room: "Hallway"},
  {x: 10, y: 0, room: "Hallway"},
  {x: 10, y: 1, room: "Hallway"},
  {x: 10, y: 2, room: "Hallway"},
  {x: 11, y: 0, room: "Hallway"},
  {x: 11, y: 1, room: "Hallway"},
  {x: 11, y: 2, room: "Hallway"},
  {x: 12, y: 1, room: "Start: C.M."},
  {x: -1, y: 1, room: "Hallway"},
  {x: -2, y: 1, room: "Hallway"},
  {x: -3, y: 1, room: "Hallway"},

  {x: 100, y: 100, room: "Police Station"},
  {x: 110, y: 110, room: "Hall"}
];
const doors = [
  {from: {x: 0, y: 1, room: "Hallway"},
  direction: "south",
     to: {x: 100, y: 100, room: "Police Station"}},
  {from: {x: 0, y: 1, room: "Hallway"},
      direction: "north",
     to: {x: 110, y: 110, room: "Hall"}},
  {from: {x: 1, y: 1, room: "Hallway"},
      direction: "north",
     to: {x: 110, y: 110, room: "Hall"}}
];

exports.map = map;
exports.doors = doors;
